class LocationData {
  final String city;
  final String country;
  bool isSelected;

  LocationData(
      {required this.city, required this.country, this.isSelected = false});
}

List<LocationData>locationList = [
  LocationData(city: 'Accra', country: 'Ghana', isSelected: false),
  LocationData(city: 'Lagos', country: 'Nigeria', isSelected: false),
  LocationData(city: 'Paris', country: 'France', isSelected: false),
  LocationData(city: 'Berlin', country: 'Germany', isSelected: false),
  LocationData(city: 'London', country: 'United Kingdom', isSelected: false),
  LocationData(city: 'New York', country: 'USA', isSelected: false),
  LocationData(city: 'Tokyo', country: 'Japan', isSelected: false),
  LocationData(city: 'Beijing', country: 'China', isSelected: false),
  LocationData(city: 'Rome', country: 'Italy', isSelected: false),
  LocationData(city: 'Sydney', country: 'Australia', isSelected: false),
  LocationData(city: 'Cairo', country: 'Egypt', isSelected: false),
  LocationData(city: 'Moscow', country: 'Russia', isSelected: false),
  LocationData(city: 'Toronto', country: 'Canada', isSelected: false),
  LocationData(city: 'Rio de Janeiro', country: 'Brazil', isSelected: false),
  LocationData(city: 'Cape Town', country: 'South Africa', isSelected: false),
  LocationData(city: 'Mexico City', country: 'Mexico', isSelected: false),
  LocationData(city: 'Dubai', country: 'United Arab Emirates', isSelected: false),
  LocationData(city: 'Seoul', country: 'South Korea', isSelected: false),
  LocationData(city: 'Mumbai', country: 'India', isSelected: false),
  LocationData(city: 'Istanbul', country: 'Turkey', isSelected: false),
  LocationData(city: 'Bangkok', country: 'Thailand', isSelected: false),
  LocationData(city: 'Barcelona', country: 'Spain', isSelected: false),
  LocationData(city: 'Los Angeles', country: 'USA', isSelected: false),
  LocationData(city: 'Amsterdam', country: 'Netherlands', isSelected: false),
  LocationData(city: 'Singapore', country: 'Singapore', isSelected: false),
  LocationData(city: 'Hanoi', country: 'Vietnam', isSelected: false),
  LocationData(city: 'Stockholm', country: 'Sweden', isSelected: false),
  LocationData(city: 'Athens', country: 'Greece', isSelected: false),
  LocationData(city: 'Lisbon', country: 'Portugal', isSelected: false),
  LocationData(city: 'Dublin', country: 'Ireland', isSelected: false),
  LocationData(city: 'Prague', country: 'Czech Republic', isSelected: false),
  LocationData(city: 'Buenos Aires', country: 'Argentina', isSelected: false),
  LocationData(city: 'Kuala Lumpur', country: 'Malaysia', isSelected: false),
  LocationData(city: 'Oslo', country: 'Norway', isSelected: false),
  LocationData(city: 'Warsaw', country: 'Poland', isSelected: false),
  LocationData(city: 'Vienna', country: 'Austria', isSelected: false),
  LocationData(city: 'Brussels', country: 'Belgium', isSelected: false),
  LocationData(city: 'Helsinki', country: 'Finland', isSelected: false),
  LocationData(city: 'Zurich', country: 'Switzerland', isSelected: false),
  LocationData(
      city: 'Johannesburg', country: 'South Africa', isSelected: false),
  LocationData(city: 'Nairobi', country: 'Kenya', isSelected: false),
  LocationData(city: 'Budapest', country: 'Hungary', isSelected: false),
  LocationData(city: 'Copenhagen', country: 'Denmark', isSelected: false),
  LocationData(city: 'Auckland', country: 'New Zealand', isSelected: false),
  LocationData(city: 'Hamburg', country: 'Germany', isSelected: false),
  LocationData(city: 'Edinburgh', country: 'United Kingdom', isSelected: false),
  LocationData(city: 'Shanghai', country: 'China', isSelected: false),
  LocationData(city: 'San Francisco', country: 'USA', isSelected: false),
  LocationData(city: 'Munich', country: 'Germany', isSelected: false),
  LocationData(city: 'Jerusalem', country: 'Israel', isSelected: false),
  LocationData(city: 'Lima', country: 'Peru', isSelected: false),
  LocationData(city: 'Edmonton', country: 'Canada', isSelected: false),
  LocationData(city: 'Riyadh', country: 'Saudi Arabia', isSelected: false),
  LocationData(city: 'Manila', country: 'Philippines', isSelected: false),
  LocationData(city: 'Doha', country: 'Qatar', isSelected: false),
  LocationData(city: 'Kolkata', country: 'India', isSelected: false),
  LocationData(city: 'Havana', country: 'Cuba', isSelected: false),
  LocationData(city: 'Nicosia', country: 'Cyprus', isSelected: false),
  LocationData(city: 'Vancouver', country: 'Canada', isSelected: false),
  LocationData(
      city: 'Luxembourg City', country: 'Luxembourg', isSelected: false),
  LocationData(city: 'Ljubljana', country: 'Slovenia', isSelected: false),
  LocationData(city: 'Montevideo', country: 'Uruguay', isSelected: false),
  LocationData(city: 'Kiev', country: 'Ukraine', isSelected: false),
  LocationData(city: 'Tehran', country: 'Iran', isSelected: false),
  LocationData(city: 'Wellington', country: 'New Zealand', isSelected: false),
  LocationData(city: 'Caracas', country: 'Venezuela', isSelected: false),
  LocationData(city: 'Ankara', country: 'Turkey', isSelected: false),
  LocationData(city: 'Helsinki', country: 'Finland', isSelected: false),
  LocationData(city: 'Bucharest', country: 'Romania', isSelected: false),
  LocationData(city: 'Dakar', country: 'Senegal', isSelected: false),
  LocationData(city: 'Belgrade', country: 'Serbia', isSelected: false),
  LocationData(city: 'Cologne', country: 'Germany', isSelected: false),
  LocationData(city: 'Panama City', country: 'Panama', isSelected: false),
  LocationData(city: 'Colombo', country: 'Sri Lanka', isSelected: false),
  LocationData(city: 'Bratislava', country: 'Slovakia', isSelected: false),
  LocationData(city: 'Tbilisi', country: 'Georgia', isSelected: false),
  LocationData(city: 'Riga', country: 'Latvia', isSelected: false),
  LocationData(city: 'Valletta', country: 'Malta', isSelected: false),
  LocationData(city: 'Tallinn', country: 'Estonia', isSelected: false),
  LocationData(city: 'Lusaka', country: 'Zambia', isSelected: false),
  LocationData(city: 'Nouakchott', country: 'Mauritania', isSelected: false),
  LocationData(city: 'Windhoek', country: 'Namibia', isSelected: false),
  LocationData(city: 'Brazzaville', country: 'Congo', isSelected: false),
  LocationData(city: 'Bishkek', country: 'Kyrgyzstan', isSelected: false),
];
